# Generated by Django 2.1 on 2018-08-17 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('authorno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, max_length=250, null=True)),
                ('sname', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'authors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Copies',
            fields=[
                ('copyno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('barcode', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('signatura', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'copies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estanterias',
            fields=[
                ('id_shelf', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('shelf', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'estanterias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Localizaciones',
            fields=[
                ('id_loc', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('loc', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'localizaciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id_subject', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'materias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoTrans',
            fields=[
                ('id_ctrans', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ctrans', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tipo_trans',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TitleAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorno', models.ForeignKey(db_column='authorno', on_delete=django.db.models.deletion.DO_NOTHING, to='biblioteca.Authors')),
            ],
            options={
                'db_table': 'title_author',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TitleMat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_subject', models.ForeignKey(db_column='id_subject', on_delete=django.db.models.deletion.DO_NOTHING, to='biblioteca.Materias')),
            ],
            options={
                'db_table': 'title_mat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('titleno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'titles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(blank=True, max_length=10, null=True)),
                ('usuario', models.CharField(blank=True, max_length=30, null=True)),
                ('copyno', models.ForeignKey(db_column='copyno', on_delete=django.db.models.deletion.DO_NOTHING, to='biblioteca.Copies')),
                ('id_ctrans', models.ForeignKey(blank=True, db_column='id_ctrans', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='biblioteca.TipoTrans')),
                ('id_loc', models.ForeignKey(blank=True, db_column='id_loc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='biblioteca.Localizaciones')),
                ('titleno', models.ForeignKey(db_column='titleno', on_delete=django.db.models.deletion.DO_NOTHING, to='biblioteca.Titles')),
            ],
            options={
                'db_table': 'transacciones',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='titlemat',
            name='titleno',
            field=models.ForeignKey(db_column='titleno', on_delete=django.db.models.deletion.DO_NOTHING, to='biblioteca.Titles'),
        ),
        migrations.AddField(
            model_name='titleauthor',
            name='titleno',
            field=models.ForeignKey(db_column='titleno', on_delete=django.db.models.deletion.DO_NOTHING, to='biblioteca.Titles'),
        ),
        migrations.AddField(
            model_name='notas',
            name='titleno',
            field=models.ForeignKey(db_column='titleno', on_delete=django.db.models.deletion.DO_NOTHING, to='biblioteca.Titles'),
        ),
        migrations.AddField(
            model_name='copies',
            name='id_loc',
            field=models.ForeignKey(blank=True, db_column='id_loc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='biblioteca.Localizaciones'),
        ),
        migrations.AddField(
            model_name='copies',
            name='id_shelf',
            field=models.ForeignKey(blank=True, db_column='id_shelf', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='biblioteca.Estanterias'),
        ),
        migrations.AddField(
            model_name='copies',
            name='titleno',
            field=models.ForeignKey(db_column='titleno', on_delete=django.db.models.deletion.DO_NOTHING, to='biblioteca.Titles'),
        ),
    ]
