# Generated by Django 2.1 on 2018-08-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='usuario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
