# Generated by Django 2.1 on 2018-08-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_auto_20180823_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
