# Generated by Django 2.1 on 2018-08-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_auto_20180823_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='titleauthor',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='titlemat',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
