# Generated by Django 2.1.1 on 2018-09-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BxBookRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_rating', models.IntegerField()),
                ('prediction', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bx_book_ratings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BxBooks',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('book_title', models.CharField(blank=True, max_length=255, null=True)),
                ('book_author', models.CharField(blank=True, max_length=255, null=True)),
                ('year_publication', models.IntegerField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('imageurls', models.CharField(blank=True, max_length=255, null=True)),
                ('imageurlm', models.CharField(blank=True, max_length=255, null=True)),
                ('imageurll', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'bx_books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BxUsers',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('age', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'bx_users',
                'managed': False,
            },
        ),
    ]
